spring:
  application:
    name: paymentservice
  cloud:
      config:
        uri: http://localhost:8090
management:
        security:
          enabled: false
name: Payment Service version 1.0
server:
  port: 21908